### ISSUE TITLE
Config option for affected items

### ISSUE THREAD

**Issue by RainbowSaber** [JustDoom/ItsStillExplosive#1]
As far as I am aware the affected blocks are currently hardcoded. For compatibility with mods that add their own explosive items, it would be amazing to add either a tag based system, where item's can simply be added to the respective tag via datapack or go for a config-file that allows listing of all items that should be affected by the custom behavior.

(Bonus points for a custom coded special interaction with alexmobs nuclear biome)

**Comment by JustDoom** [comment]
I checked the TODO for the mod and for some reason this isn't on it already. I will get around to it at some point. 

What do you mean a special interaction with alexmobs nuclear biome?

**Comment by RainbowSaber** [comment]
Oh I goofed and meant to write AlexCaves. The mod has a nuclear bomb with a special animation that takes out thousands of blocks and would need special treatment if you wanted it to trigger by throwing the nuke into lava

**Comment by JustDoom** [comment]
ah, not sure if mods will ever get support for their custom explosions sorry

**Comment by JustDoom** [comment]
I have updated the mod with a config that has a modifiable list of affected items with their explosion values. I might look into working with tags in the future to make this easier. I shall mark this as closed now.

I will upload it to curseforge later (by the time anyone sees this it probably is up there) but for now it is on modrinth https://modrinth.com/mod/its-still-explosive/versions
